# Generated by Django 5.1.2 on 2024-10-27 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SlaydHome', '0005_presentation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebDesignModel1',
            new_name='Web_Design',
        ),
    ]
